### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by cgntnr**

### CODE REVIEW

**Review by r-ismer — APPROVED** [review]
LGTM

**Review by cmsigrist — APPROVED** [review]
LGTM

**Review by Xelowak — APPROVED** [review]
LGTM ! I really think we need to call Mark when we're ready :D

**Review by Lollipoke — APPROVED** [review]
LGTM :D

**Review by betrisey — COMMENTED** [review]
Wow impressive app, can't wait to buy your data!
LGTM

**Pull request merged**
